---
layout: post
title: Exception handling with bracket
date: 2013-01-06
comments: false
---

<h1>{{ page.title }}</h1>
<div class='post'>
<h3>Introduction</h3><div>Performing IO in our pure environments can be dangerous. Who knows what people put in files that our programs are expected to read? There are tools that can help assure ourselves that we'll at least clean up if an explosion occurs.</div><div><br /></div><div>In this post, I'll talk about exception handling with IO actions using <a href="http://hackage.haskell.org/packages/archive/base/latest/doc/html/Control-Exception-Base.html#v:bracket">bracket</a>.</div><div><br /></div><h3>What is it?</h3><div><a href="http://hackage.haskell.org/packages/archive/base/latest/doc/html/Control-Exception-Base.html#v:bracket">bracket</a>&nbsp;is a function defined in Control.Exception and is defined as follows.</div><div><br /><script src="https://gist.github.com/4467064.js"></script></div><div><br />Its first parameter is a function that acquires a resource (or handle). Its second parameter is a function that releases the resource acquired in the first. The last parameter is another function that uses the acquired handle to get a result.<br /><br />The error handling comes in because the 2nd parameter, the function that releases the acquired resource is called even if an exception occurs during the execution of the last parameter.<br /><br />That's nifty. An example use of bracket looks as follows.<br /><br /><script src="https://gist.github.com/4467094.js"></script> So, there's another safety mat for when you venture into the impure world.</div></div>
<h2>Comments</h2>
<div class='comments'>
</div>
